### ISSUE TITLE
点击报错

### ISSUE THREAD

**Issue by JamesYang1624** [Airsaid/Android-PickerView-Library#5]
我的项目引用这个控件,当点击的时候报错,
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.sleep.ibreezeesr, PID: 2356
                  java.lang.IllegalStateException: Could not execute method of the activity
                      at android.view.View$1.onClick(View.java:3829)
                      at android.view.View.performClick(View.java:4444)
                      at android.view.View$PerformClick.run(View.java:18445)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5135)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at android.view.View$1.onClick(View.java:3824)
                      at android.view.View.performClick(View.java:4444) 
                      at android.view.View$PerformClick.run(View.java:18445) 
                      at android.os.Handler.handleCallback(Handler.java:733) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5135) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class com.an.base.view.tips.pickerview.widget.wheelview.WheelView
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:710)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                      at com.an.base.view.ytips.pickerview.TimePickerView.initView(TimePickerView.java:46)
                      at com.an.base.view.ytips.pickerview.TimePickerView.<init>(TimePickerView.java:38)
                      at com.sleep.ibreezee.atys.UserInfoActivity.showShengri(UserInfoActivity.java:716)
                      at com.sleep.ibreezee.atys.UserInfoActivity.ShengriClick(UserInfoActivity.java:709)
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at android.view.View$1.onClick(View.java:3824) 
                      at android.view.View.performClick(View.java:4444) 
                      at android.view.View$PerformClick.run(View.java:18445) 
                      at android.os.Handler.handleCallback(Handler.java:733) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5135) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.an.base.view.tips.pickerview.widget.wheelview.WheelView" on path: DexPathList[[zip file "/data/app/com.sleep.ibreezeesr-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.sleep.ibreezeesr-1, /vendor/lib, /system/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:562)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                      at com.an.base.view.ytips.pickerview.TimePickerView.initView(TimePickerView.java:46) 
                      at com.an.base.view.ytips.pickerview.TimePickerView.<init>(TimePickerView.java:38) 
                      at com.sleep.ibreezee.atys.UserInfoActivity.showShengri(UserInfoActivity.java:716) 
                      at com.sleep.ibreezee.atys.UserInfoActivity.ShengriClick(UserInfoActivity.java:709) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at android.view.View$1.onClick(View.java:3824) 
                      at android.view.View.performClick(View.java:4444) 
                      at android.view.View$PerformClick.run(View.java:18445) 
                      at android.os.Handler.handleCallback(Handler.java:733) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5135) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614) 
                      at dalvik.system.NativeStart.main(Native Method) 

当我注释依赖,想添加Android-PickerView时候,同步失败,错误原因:
D:\sleep\app\src\main\res\values\colors.xml
Error:(2) Attribute "pickerview_gravity" already defined with incompatible format.
Error:(2) Original attribute defined here.
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\yang\AppData\Local\Android\Sdk\build-tools\24.0.2\aapt.exe'' finished with non-zero exit value 1
请问是什么问题

**Comment by Airsaid** [comment]
请问你是怎么用这个库的呢？是引用的么？如果是的话，请贴下 XML 布局代码。
